### ISSUE TITLE
xterm跟后台是如何搭配使用的呢？

### ISSUE THREAD

**Issue by miss1323803712** [ns2250225/vue-webssh#1]
后台只是去返回终端的信息吗？xterm.js根据用户输入如何进行渲染数据呢，能否讲解下，谢谢了。

**Comment by ns2250225** [comment]
@miss1323803712  前端后端通过websocket连接，xtermjs把用户的输入通过websocket传给后台，后台运行相应命令，并把标准输出通过websocket传回给前台，前台接收到数据后进行解析渲染

**Comment by ns2250225** [comment]
@miss1323803712 可以的啊，你把这个项目运行起来看看

**Comment by miss1323803712** [comment]
我试了 没跑起来 加个q可以吗？

**Comment by ns2250225** [comment]
我加你吧，你的QQ是多少啊，我的是243027571

**Comment by miss1323803712** [comment]
加了
